# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Kelman Chiang'
tagline:          'Kelman Chiang'
description:      'Kelman Chiang'
url:              https://kelmanchiang.github.io/

author:
  name:           'Kelman Chiang'
  url:            'https://kelmanchiang.github.io/'

paginate:         3
plugins:          [jekyll-paginate]

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

collections:
	ArcGIS:
		output: true