# Dependencies
markdown:         kramdown
pygments:         true
syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Kelman Chiang'
tagline:          ''
description:      'Kelman Chiang'
url:              https://kelmanchiang.github.io/

author:
  name:           'Kelman Chiang'
  url:            'https://kelmanchiang.github.io/'

paginate:         1
plugins:          [jekyll-paginate]

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

collections:
  category:
    output: true
